//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioClub.radioclub.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class child_info
    {
        public int children_id { get; set; }
        public int member_id { get; set; }
        public string child_name { get; set; }
        public string sex { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string marital_status { get; set; }
        public Nullable<System.DateTime> marriage_date { get; set; }
        public string independent_mem_no { get; set; }
        public string child_pancard { get; set; }
        public string child_aadharcard { get; set; }
        public byte[] child_pan_image { get; set; }
        public byte[] child_aadhar_image { get; set; }
        public byte[] child_image { get; set; }
        public byte[] dob_certi_img { get; set; }
        public System.DateTime record_date { get; set; }
        public byte[] child_sign { get; set; }
    
        public virtual member_update member_update { get; set; }
    }
}
