//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioClub.radioclub.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class member_info
    {
        public int Id { get; set; }
        public string membership_no { get; set; }
        public string full_name { get; set; }
        public string pan_card { get; set; }
        public string aadhar { get; set; }
        public string email { get; set; }
    }
}
